---
title: "VAR_co2_el"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(urca)
library(lubridate)
#library(openair)
library(tseries)
library(forecast)
library(vars)
library(tidyverse)
library(hrbrthemes)

library(Hmisc)


```


# Data from Nordpool

<!-- ```{r message=FALSE, include=FALSE} -->
<!-- # El-forbrug 2017-2019 -->
<!-- consumption_dk_areas_2017_daily <- read_excel("C:/Users/rasmus dam/Dropbox/P-Sex/Data/comsumption/consumption-dk-areas_2017_daily.xlsx",  -->
<!--                                               skip = 2) -->
<!-- consumption_dk_areas_2018_daily <- read_excel("C:/Users/rasmus dam/Dropbox/P-Sex/Data/comsumption/consumption-dk-areas_2018_daily.xlsx",  -->
<!--                                               skip = 2) -->
<!-- consumption_dk_areas_2019_daily <- read_excel("C:/Users/rasmus dam/Dropbox/P-Sex/Data/comsumption/consumption-dk-areas_2019_daily.xlsx",  -->
<!--                                               skip = 2) -->

<!-- # El priser 2017-2019 -->
<!-- Elspot_priser_2017 <- read_excel("C:/Users/rasmus dam/Dropbox/P-Sex/Data/Elspot-priser/Elspot-priser_2017.xlsx") -->
<!-- Elspot_priser_2018 <- read_excel("C:/Users/rasmus dam/Dropbox/P-Sex/Data/Elspot-priser/Elspot-priser_2018.xlsx") -->
<!-- Elspot_priser_2019 <- read_excel("C:/Users/rasmus dam/Dropbox/P-Sex/Data/Elspot-priser/Elspot-priser_2019.xlsx") -->
<!-- EL_pris <- bind_rows(Elspot_priser_2017,Elspot_priser_2018,Elspot_priser_2019) %>% -->
<!--   dplyr::select(...1,DK1,DK2) %>% group_by(...1) %>% summarize(mean_price = mean(DK1,DK2)) -->



<!-- EL_forbrug <- bind_rows(consumption_dk_areas_2017_daily,consumption_dk_areas_2018_daily, -->
<!--                         consumption_dk_areas_2019_daily) %>% select(...1, DK) -->

<!-- data_forbrug_pris <- inner_join(EL_pris, EL_forbrug,by = "...1") %>% `colnames<-`(c("date", "Price", "Consumption")) -->


<!-- # co2 2017-2019 -->
<!-- co2_2017 <- read_excel("C:/Users/rasmus dam/Dropbox/P-Sex/Data/CO2/co2-2017.xlsx") -->
<!-- co2_2018 <- read_excel("C:/Users/rasmus dam/Dropbox/P-Sex/Data/CO2/co2-2018.xlsx") -->
<!-- co2_2019 <- read_excel("C:/Users/rasmus dam/Dropbox/P-Sex/Data/CO2/co2-2019.xlsx") -->
<!-- co2_fuld <- bind_rows(co2_2017,co2_2018,co2_2019) -->

<!-- co2 <- filter(co2_fuld, PriceArea == "DK1") -->
<!-- co2 <- co2[,-c(1,3)] -->

<!-- out <- co2[(order(as.Date(co2$Minutes5DK))),] -->
<!-- out <- out %>% `colnames<-`(c("date", "emission")) -->
<!-- out$date <- as_datetime(out$date) -->

<!-- #data <- out %>% mutate(date = as_date(date)) %>% group_by(date) %>% summarize(mean_emission = mean(emission)) -->
<!-- data <- out %>% mutate(date = as_date(date)) %>% group_by(date) %>% summarize(mean_emission = sum(emission)) -->

<!-- # All data -->
<!-- data_total <- bind_cols(data_forbrug_pris, data)[,-4] -->
<!-- data_total$date <- as.Date(data_total$date) -->

<!-- #save(data_total, file = "data_total.RDA") -->

<!-- data_ts <- as.ts(data_total[,-1]) -->
<!-- data_ts <- data_ts[,c(3,2,1)] -->

<!-- colnames(data_ts) <- c("Emission", "Consumption", "Price") -->
<!-- #save(data_ts, file = "data_ts.RDA") -->
<!-- ``` -->


```{r message=FALSE, include=FALSE}


load("D:/OneDrive - Aalborg Universitet/0P6/Git_repo/P6/data_total.RDA")
load("D:/OneDrive - Aalborg Universitet/0P6/Git_repo/P6/data_ts.RDA")
# pdf(file = "data_ts.pdf", height = 7.5, width = 8)
# plot.ts(data_ts)
# dev.off()


```

# plots før deseason


```{r}
gg_data_ts <- data.frame(time = as.Date("2017-1-1") + 0:1094, data_ts)

# pdf(file = "Emission.pdf",height = 2.5,width = 8)
# ggplot(data = gg_data_ts, aes(x = time, y = Emission)) +
#   geom_line(alpha = 0.8) + 
#   xlab("") +
#   scale_x_date(date_labels = "%Y %b %d")
# dev.off()
# 
# pdf(file = "Consumption.pdf",height = 2.5,width = 8)
# ggplot(data = gg_data_ts, aes(x = time, y = Consumption)) +
#   geom_line(alpha = 0.8) + 
#   xlab("") +
#   scale_x_date(date_labels = "%Y %b %d")
# dev.off()
# 
# pdf(file = "Price.pdf",height = 2.5,width = 8)
# ggplot(data = gg_data_ts, aes(x = time, y = Price)) +
#   geom_line(alpha = 0.8) + 
#   xlab("") +
#   scale_x_date(date_labels = "%Y %b %d")
# dev.off()




```




# Deseasonalize consumption

```{r}

consum <- data.frame(t =  time(data_total$Consumption), consumption = data_total$Consumption)
plot.ts(data_ts[,2])
weekend_i <- ifelse((seq_along(consum$t) -1) %% 7 ==0 | (seq_along(consum$t)) %% 7 ==0, 1,0)

nls_consum <- nls(formula = consumption ~ b_0 + b_1 * t + b_2 * I(t)^2 + c_1 * sin((t + c_2)* (2*pi)/365) + 
                    c_3 * sin((t + c_4)* 4*pi/365) + d_1 * weekend_i,
                  data = consum,
                  start = list(b_0 = 1, b_1 = 1, b_2 = 1, c_1 = 1,
                               c_2 = 1, c_3 = 1, c_4 = 1, d_1 = 1))
sum_nls_consum <- summary(nls_consum)
sum_nls_consum$parameters
# latex(sum_nls_consum$parameters)


plot(consum$t, consum$consumption)
lines(consum$t, predict(nls_consum), col = "red")


deseason_consum <- residuals(nls_consum)
plot.ts(deseason_consum)

consumption_gg <- data.frame(Time = data_total$date, Consumption = consum$consumption,
                             Season = predict(nls_consum), Deseason_consumption = deseason_consum)


# pdf(file = "season_consumption.pdf",height = 2.5,width = 8)
# ggplot(consumption_gg, aes(x = Time, y = Consumption)) +
#   geom_point() +
#   geom_line(aes(x = Time, y = Season), color = "red", alpha = 0.8, size = 0.5) +
#   scale_x_date(date_labels = "%Y %b %d") +
#   xlab("")
# dev.off()

# pdf(file = "deseason_consumption.pdf",height = 2.5,width = 8)
# ggplot(consumption_gg, aes(x = Time, y = Deseason_consumption)) +
#   geom_line(alpha = 0.8) +
#   scale_x_date(date_labels = "%Y %b %d") +
#   xlab("") +
#   ylab("Deseasonalized consumption")
# dev.off()


season_consum <- predict(nls_consum)
plot.ts(season_consum)
adf_consum <- adf.test(deseason_consum)

```

# deseason price

```{r}

Price <- data.frame(t =  time(data_total$Price), Price = data_total$Price)
plot.ts(data_ts[,1])
weekend_i <- ifelse((seq_along(Price$t) -1) %% 7 ==0 | (seq_along(Price$t)) %% 7 ==0, 1,0)

nls_Price <- nls(formula = Price ~ b_0 + b_1 * t + b_2 * I(t)^2 +
                   c_1 * sin((t + c_2)* (2*pi)/365) + 
                   c_3 * sin((t + c_4)* 4*pi/365) + d_1 * weekend_i,
                 data = Price,
                 start = list(b_0 = 1, b_1 = 1, b_2 = 1,
                              c_1 = 1, c_2 = 1, c_3 = 1, c_4 = 1, d_1 = 1))
summary(nls_Price)
# latex(summary(nls_Price)$parameters, title = "nls_price.tex")

plot(Price$t, Price$Price)
lines(Price$t, predict(nls_Price), col = "red")

deseason_Price <- residuals(nls_Price)
plot.ts(deseason_Price)
season_Price <- predict(nls_Price)
plot.ts(season_Price)
adf.test(deseason_Price)

price_gg <- data.frame(Time = data_total$date, Price = Price$Price,
                             Season = predict(nls_Price), Deseason_Price = deseason_Price)


# pdf(file = "season_Price.pdf",height = 2.5,width = 8)
# ggplot(price_gg, aes(x = Time, y = Price)) +
#   geom_point() +
#   geom_line(aes(x = Time, y = Season), color = "red", alpha = 0.8, size = 0.5) +
#   scale_x_date(date_labels = "%Y %b %d") +
#   xlab("")
# dev.off()
# 
# pdf(file = "deseason_price.pdf",height = 2.5,width = 8)
# ggplot(price_gg, aes(x = Time, y = Deseason_Price)) +
#   geom_line(alpha = 0.8) +
#   scale_x_date(date_labels = "%Y %b %d") +
#   xlab("") +
#   ylab("Deseasonalized price")
# dev.off()


```

# deseason emission

```{r}

emission <- data.frame(t =  time(data_total$mean_emission), emission = data_total$mean_emission)
plot.ts(data_ts[,3])
weekend_i <- ifelse((seq_along(emission$t) -1) %% 7 ==0 | (seq_along(emission$t)) %% 7 ==0, 1,0)

nls_emission <- nls(formula = emission ~ b_0 + b_1 * t + b_2 * I(t)^2 +
                      c_1 * sin((t + c_2)* (2*pi)/365) + 
                      c_3 * sin((t + c_4)* 4*pi/365) + d_1 * weekend_i,
                    data = emission,
                    start = list(b_0 = 1, b_1 = 1, b_2 = 1,
                                 c_1 = 1, c_2 = 1, c_3 = 1, c_4 = 1, d_1 = 1))
# summary(nls_emission)

latex(summary(nls_emission)$parameters, title = "nls_emission.tex")

plot(emission$t, emission$emission)
lines(emission$t, predict(nls_emission), col = "red")

deseason_emission <- residuals(nls_emission)
plot.ts(deseason_emission)
season_emission <- predict(nls_emission)
plot.ts(season_emission)
adf.test(deseason_emission)


emission_gg <- data.frame(Time = data_total$date, Emission = emission$emission,
                             Season = predict(nls_emission), Deseason_Emission = deseason_emission)

# 
# pdf(file = "season_emission.pdf",height = 2.5,width = 8)
# ggplot(emission_gg, aes(x = Time, y = Emission)) +
#   geom_point() +
#   geom_line(aes(x = Time, y = Season), color = "red", alpha = 0.8, size = 0.5) +
#   scale_x_date(date_labels = "%Y %b %d") +
#   xlab("")
# dev.off()
# 
# pdf(file = "deseason_emission.pdf",height = 2.5,width = 8)
# ggplot(emission_gg, aes(x = Time, y = Deseason_Emission)) +
#   geom_line(alpha = 0.8) +
#   scale_x_date(date_labels = "%Y %b %d") +
#   xlab("") +
#   ylab("Deseasonalized emission")
# dev.off()


```



```{r}
plot.ts(data_ts)

# consumption looks seasonal, we deseasonalized this earlier and will use that now
# Evt deseason dem alle, evt ikke
data_ts[,"Consumption"] <- as.ts(deseason_consum)
data_ts[,"Price"] <- as.ts(deseason_Price)
data_ts[,"Emission"] <- as.ts(deseason_emission)



# data_ts[,"Price"] <- data_ts[,"Price"] - mean(data_ts[,"Price"])
# data_ts[,"mean_emission"] <- data_ts[,"mean_emission"] - mean(data_ts[,"mean_emission"])
plot.ts(data_ts)

```

# Plots

```{r}
gg_data_ts <- data.frame(time = as.Date("2017-1-1") + 0:1094, data_ts)
ggplot(data = gg_data_ts, aes(x = time, y = Emission)) +
  geom_line() + 
  xlab("") +
  scale_x_date(date_labels = "%Y %b %d")

ggplot(data = gg_data_ts, aes(x = time, y = Consumption)) +
  geom_line() + 
  xlab("") +
  scale_x_date(date_labels = "%Y %b %d")

ggplot(data = gg_data_ts, aes(x = time, y = Price)) +
  geom_line() + 
  xlab("") +
  scale_x_date(date_labels = "%Y %b %d")


```


```{r}
adf.test(data_ts[,1])
adf.test(data_ts[,2])
adf.test(data_ts[,3])

acf(data_ts)
pacf(data_ts)


VAR_result <- VARselect(data_ts, lag.max = 10, type = "both")
VAR_result$selection
latex(VAR_result$selection)

p1ct <- VAR(data_ts, p = 3)
roots(p1ct)
summary(p1ct)
plot(p1ct)
p1ct

ser11 <- serial.test(p1ct, lags.pt = 16, type = "PT.asymptotic")
ser11
plot(ser11)

norm1 <- normality.test(p1ct)
norm1$jb.mul
plot(norm1)

fanchart(predict(p1ct, n.ahead = 20), xlim = c(1050,1150))

#impuls <- irf(p1ct, impulse = "Consumption",response = c("Price", "mean_emission"), boot = F)
impuls_iorto <- irf(p1ct, boot = F, ortho = F, cumulative = F, n.ahead = 20) # shocksne er sd, https://stackoverflow.com/questions/47309757/shock-magnitude-in-irf-of-vars-package-r
impuls_orto <- irf(p1ct, boot = F, ortho = T, cumulative = F, n.ahead = 20)

plot(impuls_iorto)
impuls_iorto

impuls_orto
plot(impuls_orto)

forecast_error <- fevd(p1ct)
print(forecast_error)
plot(forecast_error)


summary(p1ct)$varresult$Price$sigma
summary(p1ct)$varresult$Consumption$sigma
summary(p1ct)$varresult$mean_emission$sigma

arch1 <- arch.test(p1ct)
print(arch1)
plot(arch1)

plot(stability(p1ct))

summary(ca.jo(data_total[,-1], type = "trace", ecdet = "trend", K = 8, spec = "transitory"))


# causality
p1ct$varresult
causality(p1ct, cause = c("Consumption","mean_emission"))
causality(p1ct, cause = "mean_emission", vcov.=vcovHC(p1ct))
causality(p1ct, cause = "mean_emission")
causality(p1ct, cause = "Price")
causality(p1ct, cause = "Consumption")


granger <- function(data) {
  for (i in 1:ncol(data)) {
    for (j in 1:ncol(data)) {
      if (!(i==j)) {
        cat("col = ", i, "col = ", j, "\n")
        print(grangertest(data[,i], data[,j]))
      }
    }
  }
}
granger(data_ts)



Acoef(p1ct)
vars::Bcoef(p1ct)
vars::causality(p1ct)
vars::stability(p1ct)
BQ(p1ct)
vars::Phi(p1ct)
vars::Psi(p1ct)
summary(p1ct)



apply(data_ts, 2, mean)
```

# forsøg på noget svar model, ikke sikker på hvad de matricer der skal være

```{r}

amat <- diag(3)
diag(amat) <- NA

# SVAR(p1ct, Amat = amat,estmethod = "scoring", hessian = T, Bmat = NULL,
#     max.iter = 100, maxls = 1000, conv.crit = 1.0e-8)

svar_result <- SVAR(x = p1ct, estmethod = "direct", Amat = amat)


irf_svar <- irf(svar_result, boot = F)
plot(irf_svar)



vars::Phi(p1ct)
vars::Psi(p1ct)

```


<!-- ```{r virker ikke forsog paa deaseasonalize, eval=FALSE, include=FALSE} -->

<!-- consum <- data.frame(t =  time(data_total$Consumption), consumption = data_total$Consumption) -->

<!-- lm_desea <- lm(consumption ~ t + sin(t * (2*pi)/365) + sin(t * (4*pi)/365), data = consum) -->

<!-- lm_desea <- lm() -->
<!-- summary(lm_desea) -->

<!-- plot_data <- bind_cols(consum,predicted = predict(lm_desea)) -->

<!-- ggplot(plot_data, aes(t,consumption)) + -->
<!--   geom_point() +  -->
<!--   geom_point(aes(t,predicted)) -->

<!-- plot.ts(plot_data$consumption - plot_data$predicted) -->


<!-- #fit <- lm(unlist(dk1f[2]) ~ t + I(t^2)+ -->
<!-- #            sin((t)(2pi)/(365))+cos((t)(2pi)/365)+ -->
<!-- #            sin((4pi/365)t) + cos((4pi/365)t)+ -->
<!-- #            sin((8pi/365)t) + cos((8pi/365)t) +  -->
<!-- #            dummy.sat + dummy.sun) -->
<!-- #summary(fit) -->

<!-- consum_ts <- ts(data_total$Consumption) -->
<!-- findfrequency(consum_ts) -->
<!-- consum_ts <- ts(data_total$Consumption, frequency = 7) -->
<!-- deco_consum_ts <- decompose(consum_ts) -->
<!-- plot(seasadj(deco_consum_ts)) -->
<!-- season1 <- seasadj(deco_consum_ts) -->
<!-- findfrequency(season1) -->
<!-- s1ts <- ts(seasadj(deco_consum_ts), frequency = 365) -->
<!-- deco_s1ts <- decompose(s1ts) -->
<!-- plot(seasadj(deco_s1ts)) -->
<!-- plot(consum_ts) -->
<!-- findfrequency(seasadj(deco_s1ts)) -->
<!-- ``` -->



```{r}
data_test_time <- data.frame(
  day = as.Date("2017-06-14") - 0:364,
  value = runif(365) + seq(-140, 224)^2 / 10000
)

p <- ggplot(data, aes(x=day, y=value)) +
  geom_line( color="steelblue") + 
  geom_point() +
  xlab("") +
  theme_ipsum() +
  theme(axis.text.x=element_text(angle=60, hjust=1)) +
  scale_x_date(limit=c(as.Date("2017-01-01"),as.Date("2017-02-11"))) +
  ylim(0,1.5)

p


```

